import {useDeferredValue,useEffect,useMemo,useRef,useState} from 'react';
import {Archive,ArrowLeft,ArrowRight,Check,ChevronRight,Database,FileClock,FileUp,FolderOpen,HardDrive,History,Link2,LockKeyhole,MoreHorizontal,RefreshCw,Search,ShieldCheck,UnlockKeyhole,X} from 'lucide-react';
import {api,duration,humanize,number,useResource} from '../api.js';
import {Badge,Empty,Metadata,Status} from './Common.jsx';
import './DataStores.css';
import SourcePropagation from './SourcePropagation.jsx';
import {availabilityLabel,availabilityExplanation} from '../metadataRefresh.js';

const PAGE_SIZE=50;
const actions={
  freeze:{label:'Freeze registration',verb:'Freeze',Icon:LockKeyhole,explanation:'Locks query participation and archive controls. It does not change protocol curation or source-file access.'},
  unfreeze:{label:'Unfreeze registration',verb:'Unfreeze',Icon:UnlockKeyhole,explanation:'Unlocks query participation and archive controls. Existing scientific selections stay unchanged.'},
  exclude:{label:'Exclude source from new queries',verb:'Exclude from queries',Icon:Database,explanation:'New queries will skip this source. Existing working datasets stay unchanged until you propagate the change. Raw data and earlier saved exports are kept.'},
  include:{label:'Include source in new queries',verb:'Include in queries',Icon:Database,explanation:'Allows this source in new queries, even if its registration is archived. Propagate changes to update existing working datasets. Earlier saved exports stay unchanged.'},
  archive:{label:'Archive from the current list',verb:'Archive registration',Icon:Archive,explanation:'Moves this registration to the Archived list. Query participation, working datasets, raw files and earlier exports are unchanged.'},
  restore:{label:'Restore registration to current list',verb:'Restore registration',Icon:RefreshCw,explanation:'Returns this registration to the Current list. Its query participation and working datasets stay unchanged.'},
};
const count=value=>typeof value==='number'?number(value):'—';
function timestamp(value){
  if(!value)return 'Not recorded';
  const date=new Date(value);return Number.isNaN(date.getTime())?String(value):date.toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZoneName:'short'});
}
function fileSize(value){if(!Number.isFinite(value)||value<0)return 'Not recorded';if(value<1000)return `${value} B`;const units=['KB','MB','GB','TB'];let size=value/1000,index=0;while(size>=1000&&index<units.length-1){size/=1000;index++;}return `${size.toLocaleString(undefined,{maximumFractionDigits:1})} ${units[index]}`;}
function checkedTime(value){if(!value)return 'Not checked';const date=new Date(value);return Number.isNaN(date.getTime())?'Timestamp unavailable':date.toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'});}
function StoreState({source}){return <div className="ds-state" title={availabilityExplanation(source.file_status)}><Badge kind={source.file_status==='available'?'success':'warning'}>{availabilityLabel(source.file_status)}</Badge>{source.state?.frozen&&<Badge><LockKeyhole size={11}/> Frozen</Badge>}{source.state?.archived&&<Badge><Archive size={11}/> Archived</Badge>}</div>;}
function QueryParticipation({source,onStage,disabled}){
  const excluded=source.state?.query_excluded,frozen=source.state?.frozen===true,known=typeof excluded==='boolean';
  return <div className="ds-query-participation"><span className={known?(excluded?'ds-query-excluded':'ds-query-included'):'ds-query-unknown'}><i/>{known?(excluded?'Excluded from queries':'Included in queries'):'Participation not reported'}</span><button disabled={disabled||frozen||!known} onClick={()=>onStage(source,excluded?'include':'exclude')} title={frozen?'Unfreeze registration to change query participation':excluded?'Allow this source in new queries':'Skip this source in new queries'}>{excluded?'Include in queries':'Exclude from queries'}</button></div>;
}
function StoreActions({source,onStage,onPropagate,disabled}){
  const state=source.state || {},frozen=state.frozen===true;
  return <div className="ds-row-actions">{onPropagate&&<button disabled={disabled} onClick={()=>onPropagate(source)} title="Preview complete saved-query changes before updating working datasets"><RefreshCw size={13}/> Propagate changes</button>}
    <details className="ds-manage"><summary aria-disabled={disabled} onClick={event=>{if(disabled)event.preventDefault();}}><MoreHorizontal size={15}/> Manage</summary><div><button disabled={disabled} onClick={()=>onStage(source,frozen?'unfreeze':'freeze')} title="Freeze locks participation and archive controls; epoch curation stays editable">{frozen?<UnlockKeyhole size={13}/>:<LockKeyhole size={13}/>} {frozen?'Unfreeze':'Freeze registration'}</button><button disabled={disabled||frozen} onClick={()=>onStage(source,state.archived?'restore':'archive')} title={frozen?'Unfreeze registration before changing list visibility':'Changes list visibility only; query participation is separate'}>{state.archived?<RefreshCw size={13}/>:<Archive size={13}/>} {state.archived?'Restore to current list':'Archive registration'}</button></div></details>
  </div>;
}
function LifecycleForm({pending,reason,setReason,busy,error,onCancel,onSubmit}){
  const action=actions[pending.action],Icon=action.Icon;
  return <form className={`ds-lifecycle-form ds-action-${pending.action}`} onSubmit={onSubmit} aria-label={`${action.label} confirmation`}>
    <div className="ds-action-explanation"><Icon size={17}/><div><strong>{action.label}: {pending.source.filename}</strong><p>{action.explanation}</p></div><button type="button" className="icon-button" onClick={onCancel} disabled={busy} aria-label="Cancel store action"><X size={15}/></button></div>
    <div className="ds-action-fields"><label>Reason <small>optional</small><input value={reason} onChange={event=>setReason(event.target.value)} maxLength={1000} disabled={busy} placeholder="Why is this store changing state?"/></label><button type="button" onClick={onCancel} disabled={busy}>Cancel</button><button className="primary" disabled={busy} type="submit">{busy?'Recording change…':action.verb}</button></div>
    {error&&<p className="ds-operation-error" role="alert">{error}</p>}
  </form>;
}
function EventDetails({event}){
  const [open,setOpen]=useState(false);
  const detail=useResource(open?`/events/${event.event_uuid}`:null);
  return <details onToggle={event=>setOpen(event.currentTarget.open)}><summary>Recorded event details</summary>{open&&<Status {...detail} retry={detail.reload}>{detail.data&&<pre>{JSON.stringify(detail.data,null,2)}</pre>}</Status>}</details>;
}
function StoreTimeline({sha,revision,onLogs}){
  const [offset,setOffset]=useState(0);
  const events=useResource(`/data-stores/${sha}/events?limit=50&offset=${offset}`,revision);
  useEffect(()=>setOffset(0),[sha]);
  return <section className="ds-timeline"><div className="ds-section-heading"><h2><History size={16}/> Source activity</h2><button onClick={events.reload} disabled={events.loading} aria-label="Refresh source activity"><RefreshCw size={14}/></button>{onLogs&&<button onClick={onLogs}>Master log <ArrowRight size={13}/></button>}</div>{events.data?.attribution?.unresolved_project_history_references>0&&<p className="ds-evidence-note">Some historical query or export references in this project could not be resolved. Source activity may be incomplete.</p>}<Status {...events} retry={events.reload}>{events.data?.events?.length?<ol>{events.data.events.map(event=><li key={event.event_uuid}><div className="ds-event-mark"><FileClock size={14}/></div><div><div className="ds-event-title"><strong>{humanize(event.action).replace(/_/g,' ')}</strong><time>{timestamp(event.occurred_at)}</time></div><p>{event.actor || 'Actor not recorded'}{event.payload?.reason?` · ${event.payload.reason}`:''}</p>{event.source_link&&<div className="ds-event-evidence"><span>Linked by {(Array.isArray(event.source_link.basis)?event.source_link.basis:[]).map(value=>humanize(value).replace(/_/g,' ')).join(', ') || 'source evidence'}</span>{Number.isInteger(event.source_link.affected_epoch_count)&&<span>{number(event.source_link.affected_epoch_count)} linked source epochs</span>}</div>}<EventDetails event={event}/></div></li>)}</ol>:<p className="ds-no-events">No source-linked activity is recorded. Validation time alone does not establish when a file was imported.</p>}</Status><div className="ds-event-pages"><button disabled={!offset||events.loading} onClick={()=>setOffset(Math.max(0,offset-50))} aria-label="Previous source events"><ArrowLeft size={14}/></button><span>{events.data?.events?.length?offset+1:0}–{offset+(events.data?.events?.length || 0)}</span><button disabled={!events.data?.has_more||events.loading} onClick={()=>setOffset(offset+50)} aria-label="Next source events"><ArrowRight size={14}/></button></div></section>;
}
function SourceContents({source}){
  const [protocolLimit,setProtocolLimit]=useState(8),[typeLimit,setTypeLimit]=useState(8);
  const counts=source.counts || {},protocols=source.acquisition_protocols || [],types=source.cell_types || [];
  return <section className="ds-contents" aria-label="Recorded source contents"><div className="ds-section-heading"><h2><HardDrive size={16}/> Inside this H5 source</h2><span>Catalog contents · preserved when archived</span></div>
    <div className="ds-content-totals">{[['Cells',count(counts.cells)],['Epochs',count(counts.epochs)],['Recorded time',duration(counts.duration_seconds)],['Epoch blocks',count(counts.blocks)],['Response streams',count(counts.responses)],['Stimulus streams',count(counts.stimuli)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <div className="ds-content-distributions"><section><h3>Recorded protocols <small>epochs</small></h3>{protocols.slice(0,protocolLimit).map(item=><div className="ds-content-bar-row" key={item.name}><div><span title={item.name}>{humanize(item.name?.split('.').at(-1)) || 'Not recorded'}</span><strong>{count(item.epoch_count)}</strong></div><div className="ds-content-bar-track"><i style={{width:`${Math.min(100,(item.epoch_count || 0)/Math.max(1,counts.epochs || 0)*100)}%`}}/></div><small>{count(item.cells)} cells · {duration(item.duration_seconds)}</small></div>)}{protocols.length>protocolLimit&&<button onClick={()=>setProtocolLimit(value=>value+8)}>Show more protocols</button>}</section>
      <section><h3>Recorded cell types <small>unique source cells</small></h3>{types.length?types.slice(0,typeLimit).map((item,index)=><div className="ds-content-bar-row ds-type-bar" key={item.name ?? index}><div><span>{humanize(item.name) || 'Type not recorded'}</span><strong>{count(item.cells)}</strong></div><div className="ds-content-bar-track"><i style={{width:`${Math.min(100,(item.cells || 0)/Math.max(1,counts.cells || 0)*100)}%`}}/></div><small>{count(item.epochs)} epochs · {duration(item.duration_seconds)}</small></div>):<p>Cell type distribution is not recorded.</p>}{types.length>typeLimit&&<button onClick={()=>setTypeLimit(value=>value+8)}>Show more cell types</button>}</section>
    </div>
  </section>;
}
function StoreDetail({source,revision,onBack,onStage,onPropagate,busy,pending,form,onProtocol,onFiles,onLogs}){
  const [protocolLimit,setProtocolLimit]=useState(20),[exportLimit,setExportLimit]=useState(20);
  const protocols=source.protocols || [],exports=source.exports || [];
  return <div className="ds-detail"><div className="ds-detail-title"><button onClick={onBack}><ArrowLeft size={15}/> All data stores</button><StoreState source={source}/><QueryParticipation source={source} onStage={onStage} disabled={busy}/><StoreActions source={source} onStage={onStage} onPropagate={onPropagate} disabled={busy}/></div>
    {pending?.source.source_sha256===source.source_sha256&&form}
    <div className="ds-detail-identity"><HardDrive size={25}/><div><h2>{source.filename}</h2><p>{source.source_path || 'Source path not recorded'}</p></div>{onFiles&&<button onClick={onFiles}><FolderOpen size={14}/> Project files</button>}</div>
    <SourceContents source={source}/>
    <div className="ds-detail-grid"><div>
      <section className="ds-source-facts"><h2><ShieldCheck size={16}/> Source identity & registration</h2><dl>
        <div><dt>Source SHA-256</dt><dd className="ds-mono">{source.source_sha256}</dd></div><div><dt>Recorded import time</dt><dd>{timestamp(source.imported_at)}{!source.imported_at&&<small>No source-specific import timestamp is recorded.</small>}</dd></div><div><dt>Availability checked</dt><dd>{checkedTime(source.checked_at)}<small>{availabilityExplanation(source.file_status)}</small></dd></div><div><dt>File last modified</dt><dd>{timestamp(source.modified_at)}<small>Filesystem timestamp; independent of import time.</small></dd></div><div><dt>Validation recorded</dt><dd>{timestamp(source.validated_at)}</dd></div><div><dt>File size now / registered</dt><dd>{fileSize(source.size_bytes)} / {fileSize(source.recorded_size_bytes)}</dd></div><div><dt>Recording dates</dt><dd>{source.recording_dates?.length?source.recording_dates.join(' · '):'Not recorded'}</dd></div><div><dt>Registration version</dt><dd>{Number.isInteger(source.state?.version)?source.state.version:'Not recorded'}</dd></div><div><dt>Last lifecycle change</dt><dd>{timestamp(source.state?.updated_at)}{source.state?.actor&&<small>{source.state.actor_kind==='local_user'?'Recorded by':'Actor label'}: {source.state.actor}</small>}{source.state?.server_actor&&source.state.server_actor!==source.state.actor&&<small>Server user: {source.state.server_actor}</small>}{source.state?.reason&&<small>{source.state.reason}</small>}</dd></div>
      </dl><p className="ds-scope-note">Query participation controls new queries. Archive only changes which list shows this registration. Propagation updates working datasets explicitly; raw files and earlier saved exports are preserved.</p></section>
      <section className="ds-links"><div className="ds-section-heading"><h2><Database size={16}/> Linked protocol workspaces</h2><Badge>{count(source.counts?.protocol_workspaces)}</Badge></div>{protocols.length?<div className="ds-linked-list">{protocols.slice(0,protocolLimit).map(protocol=><button key={protocol.protocol_uuid} disabled={!onProtocol} onClick={()=>onProtocol?.(protocol.protocol_uuid)}><span><strong>{humanize(protocol.name)}</strong><small>{count(protocol.epoch_count)} source epochs{protocol.working_dataset_version>0?` · dataset version ${protocol.working_dataset_version}`:' · Saved source query'}</small></span><ArrowRight size={14}/></button>)}{protocols.length>protocolLimit&&<button onClick={()=>setProtocolLimit(limit=>limit+20)}>Show more protocols</button>}</div>:<p>No protocol workspace links are recorded for this source.</p>}</section>
      <section className="ds-links"><div className="ds-section-heading"><h2><Link2 size={16}/> Saved dataset connections</h2><Badge>{count(source.counts?.exports)}</Badge></div>{exports.length?<div className="ds-export-list">{exports.slice(0,exportLimit).map(item=><div key={item.dataset_uuid}><strong>{item.name || item.dataset_uuid}</strong><span>{count(item.epoch_count)} source epochs · {timestamp(item.created_at)}</span><small className="ds-mono">{item.dataset_uuid}</small>{item.download_url&&<a href={item.download_url} download>Saved export <ArrowRight size={12}/></a>}</div>)}{exports.length>exportLimit&&<button onClick={()=>setExportLimit(limit=>limit+20)}>Show more exports</button>}</div>:<p>No saved export links are recorded for this source.</p>}</section>
      <details className="ds-registration-metadata"><summary>Recorded protocols & parser metadata</summary><Metadata title="Source parser metadata" data={source.parser&&Object.keys(source.parser).length?source.parser:{status:'No parser metadata recorded'}}/><Metadata title="Acquisition protocols" data={Object.fromEntries((source.acquisition_protocols || []).map(item=>[item.name,{epochs:item.epoch_count,cells:item.cells}]))}/></details>
    </div><StoreTimeline sha={source.source_sha256} revision={revision} onLogs={onLogs}/></div>
  </div>;
}
export default function DataStores({revision=0,onChange,onImport,onProtocol,onFiles,onLogs,session=null,onSession}){
  const saved=useRef(session).current;
  const [tab,setTab]=useState(saved?.tab||'active'),[search,setSearch]=useState(saved?.search||''),[offset,setOffset]=useState(saved?.offset||0),[selected,setSelected]=useState(saved?.selected||null),[version,setVersion]=useState(0);
  const [propagationSource,setPropagationSource]=useState(null),[changedSource,setChangedSource]=useState(null);
  const [pending,setPending]=useState(null),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(saved?.wasBusy?'A source action was in progress when you left. Check its activity before retrying.':'');
  const query=useDeferredValue(search.trim().toLowerCase());
  const inventory=useResource('/data-stores',`${revision}:${version}`);
  const sources=inventory.data?.data_stores || [];
  const filtered=useMemo(()=>sources.filter(source=>(tab==='all'||(tab==='archived'?source.state?.archived:!source.state?.archived))&&`${source.filename} ${source.source_path} ${source.source_sha256}`.toLowerCase().includes(query)),[sources,tab,query]);
  const sizedFiles=filtered.filter(source=>Number.isFinite(source.size_bytes)&&source.size_bytes>=0);
  const listedBytes=sizedFiles.reduce((sum,source)=>sum+source.size_bytes,0);
  const detailPath=selected?`/data-stores/${selected}`:null;
  const detail=useResource(detailPath,`${revision}:${version}`);
  const selectedInventory=sources.find(item=>item.source_sha256===selected);
  const loadedSource=detail.data?.source_sha256===selected?detail.data:null;
  const newerAvailability=selectedInventory?.checked_at&&(!loadedSource?.checked_at||Date.parse(selectedInventory.checked_at)>=Date.parse(loadedSource.checked_at));
  const source=loadedSource&&newerAvailability?{...loadedSource,...Object.fromEntries(['checked_at','file_status','size_bytes','modified_at'].map(key=>[key,selectedInventory[key]]))}:loadedSource;
  const detailLoading=!!selected&&!detail.error&&(detail.loading||detail.path!==detailPath);
  const actionsBusy=busy||inventory.loading||detailLoading;
  useEffect(()=>{onSession?.({tab,search,offset,selected,wasBusy:busy});},[tab,search,offset,selected,busy,onSession]);
  const previousFilter=useRef({tab,query});
  useEffect(()=>{if(previousFilter.current.tab!==tab||previousFilter.current.query!==query)setOffset(0);previousFilter.current={tab,query};},[tab,query]);
  useEffect(()=>{if(inventory.data&&!inventory.loading)setOffset(current=>Math.min(current,Math.max(0,Math.floor((filtered.length-1)/PAGE_SIZE)*PAGE_SIZE)));},[filtered.length,inventory.data,inventory.loading]);
  function stage(source,action){setPending({source,action});setReason('');setError('');setMessage('');}
  async function changeState(event){
    event.preventDefault();if(busy||!pending)return;setBusy(true);setError('');
    try{if(!Number.isInteger(pending.source.state?.version))throw new Error('Registration version is missing. Refresh this store.');const result=await api(`/data-stores/${pending.source.source_sha256}/state`,{method:'POST',body:{action:pending.action,expected_version:pending.source.state.version,reason:reason.trim()}});if(!result.state||!result.event_uuid)throw new Error('No recorded state change was returned. Refresh the store before retrying.');setMessage(`${actions[pending.action].verb} recorded for ${pending.source.filename}.`);setChangedSource(['exclude','include'].includes(pending.action)?pending.source:null);setPending(null);setVersion(value=>value+1);onChange?.();}
    catch(error){setError(`${error.message} Refresh the inventory before retrying a conflicting change.`);}finally{setBusy(false);}
  }
  function refresh(){if(busy)return;setPending(null);setError('');inventory.reload();}
  const form=pending?<LifecycleForm pending={pending} reason={reason} setReason={setReason} busy={actionsBusy} error={error} onCancel={()=>setPending(null)} onSubmit={changeState}/>:null;
  const counts=inventory.data?.counts || {};
  const openPropagation=store=>{setPending(null);setPropagationSource(store);};
  const propagated=()=>{setVersion(value=>value+1);onChange?.();};
  return <div className="page data-stores"><div className="page-heading"><div><div className="eyebrow">PROJECT SOURCES</div><h1>Data stores</h1><p>Imported H5 recordings and their connections to project datasets.</p></div><div className="ds-heading-actions">{onImport&&<button onClick={onImport} disabled={busy}>Import progress</button>}<button disabled={busy||inventory.loading} onClick={refresh} title="Check source paths and file sizes; no full checksum scan"><RefreshCw size={15} className={inventory.loading?'spin':''}/> Check sources</button>{onImport&&<button className="primary" onClick={onImport} disabled={busy}><FileUp size={15}/> Add H5</button>}</div></div>
    <div className="ds-availability-check" role="status"><span><strong>Availability checked:</strong> {checkedTime(inventory.data?.checked_at || inventory.data?.counts?.checked_at)}</span><span>Lightweight path and size check · file contents are verified separately when read or refreshed.</span></div>
    {message&&<div className="ds-operation-result" role="status"><Check size={15}/>{message}{changedSource&&<button className="ds-preview-propagation" onClick={()=>openPropagation(sources.find(item=>item.source_sha256===changedSource.source_sha256) || changedSource)}>Preview protocol updates <ArrowRight size={13}/></button>}<button onClick={()=>setMessage('')} aria-label="Dismiss result"><X size={14}/></button></div>}
    {!propagationSource&&selected&&(!source||detail.error||inventory.error)&&<button className="ds-detail-back" onClick={()=>{setSelected(null);setPending(null);}}><ArrowLeft size={14}/> Back to data stores</button>}
    <Status {...inventory} retry={refresh}>{propagationSource?<SourcePropagation key={propagationSource.source_sha256} source={sources.find(item=>item.source_sha256===propagationSource.source_sha256) || propagationSource} onBack={()=>setPropagationSource(null)} onChange={propagated} onProtocol={onProtocol}/>:selected?<Status {...detail} data={source} loading={detailLoading} retry={detail.reload}>{source&&<StoreDetail key={source.source_sha256} source={source} revision={`${revision}:${version}`} onBack={()=>{setSelected(null);setPending(null);}} onStage={stage} onPropagate={openPropagation} busy={actionsBusy} pending={pending} form={form} onProtocol={onProtocol} onFiles={onFiles} onLogs={onLogs}/>}</Status>:<>
      <div className="ds-toolbar"><nav aria-label="Data store visibility">{[['active','Current'],['archived','Archived'],['all','All']].map(([value,label])=><button key={value} className={tab===value?'active':''} aria-pressed={tab===value} disabled={busy} onClick={()=>{setTab(value);setPending(null);}}>{label}<span>{count(value==='all'?counts.total:counts[value])}</span></button>)}</nav><label className="ds-search"><Search size={15}/><input value={search} onChange={event=>setSearch(event.target.value)} aria-label="Search data stores" placeholder="Find filename, path or source hash"/></label><span className="ds-frozen-count"><LockKeyhole size={13}/>{count(counts.frozen)} frozen</span></div>
      <div className="ds-size-summary"><HardDrive size={16}/><strong>{sizedFiles.length?fileSize(listedBytes):filtered.length?'Size unavailable':'0 B'}</strong><span>across {number(filtered.length)} listed H5 {filtered.length===1?'file':'files'}</span>{sizedFiles.length<filtered.length&&<small>{number(filtered.length-sizedFiles.length)} file sizes unavailable</small>}</div>
      <section className="ds-table-section" aria-label="Imported H5 recordings"><div className="ds-table-scroll"><table className="ds-table"><thead><tr><th>H5 data store</th><th>File size</th><th>Availability / state</th><th>New queries</th><th>Cells / epochs</th><th>Import / file modification</th><th>Lifecycle</th></tr></thead><tbody>{filtered.slice(offset,offset+PAGE_SIZE).map(item=><StoreRows key={item.source_sha256} source={item} onOpen={()=>{setSelected(item.source_sha256);setPending(null);}} onStage={stage} onPropagate={openPropagation} busy={actionsBusy} form={pending?.source.source_sha256===item.source_sha256?form:null}/>)}</tbody></table></div>{!filtered.length&&<Empty title={query?'No matching data stores':tab==='archived'?'No archived data stores':tab==='active'?'No current store registrations':'No registered data stores'}>{query?'Try a filename, source path or SHA-256 prefix.':tab==='archived'?'Archived registrations appear here; their scientific records remain accessible.':tab==='active'&&counts.total>0?'Switch to Archived or All to find existing sources. Their scientific records remain available.':'Add an H5 recording to register a source.'}</Empty>}<div className="ds-table-footer"><span>{number(filtered.length)} matching registrations · query participation is independent of list visibility</span><div><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-PAGE_SIZE))} aria-label="Previous data stores"><ArrowLeft size={14}/></button><span>{filtered.length?offset+1:0}–{Math.min(offset+PAGE_SIZE,filtered.length)}</span><button disabled={offset+PAGE_SIZE>=filtered.length} onClick={()=>setOffset(offset+PAGE_SIZE)} aria-label="Next data stores"><ArrowRight size={14}/></button></div></div></section>
    </>}</Status>
  </div>;
}
function StoreRows({source,onOpen,onStage,onPropagate,busy,form}){
  return <><tr><td><button className="ds-store-name" onClick={onOpen}><HardDrive size={17}/><span><strong>{source.filename}</strong><small>{source.source_sha256?.slice(0,12)}…</small></span><ChevronRight size={14}/></button></td><td className="ds-file-size" title={Number.isFinite(source.size_bytes)?`${number(source.size_bytes)} bytes · latest source check`:'Current file size unavailable'}><strong>{fileSize(source.size_bytes ?? source.recorded_size_bytes)}</strong>{source.size_bytes==null&&Number.isFinite(source.recorded_size_bytes)?<small>Recorded at import</small>:source.recorded_size_bytes!=null&&source.size_bytes!==source.recorded_size_bytes?<small>At import: {fileSize(source.recorded_size_bytes)}</small>:null}</td><td><StoreState source={source}/><small className="ds-checked-time">Checked {checkedTime(source.checked_at)}</small></td><td><QueryParticipation source={source} onStage={onStage} disabled={busy}/></td><td className="ds-table-counts"><strong>{count(source.counts?.cells)} cells</strong><span>{count(source.counts?.epochs)} epochs</span></td><td className="ds-times"><span><small>Imported</small>{timestamp(source.imported_at)}</span><span><small>File modified</small>{timestamp(source.modified_at)}</span></td><td><StoreActions source={source} onStage={onStage} onPropagate={onPropagate} disabled={busy}/></td></tr>{form&&<tr className="ds-action-row"><td colSpan={7}>{form}</td></tr>}</>;
}
