import {useState} from 'react';
import {ListFilter,X,Plus,Trash2} from 'lucide-react';
import {useResource} from '../api.js';
import {readTagRules,compileTagRules,clearTagFilters,tagFilterLabel} from '../protocolViewFilter.js';
import './ProtocolViewFilter.css';
const blank=()=>({scope:'effective',comparison:'is',value:''});
export default function ProtocolViewFilter({filters={},onChange,revision,disabled=false}){
  const [open,setOpen]=useState(false),[mode,setMode]=useState('all_epochs'),[logic,setLogic]=useState('all'),[rules,setRules]=useState([blank()]),[query,setQuery]=useState(''),[error,setError]=useState('');
  const active=!!tagFilterLabel(filters);
  const options=useResource(open&&mode==='rules'?`/annotation-tags?q=${encodeURIComponent(query)}&limit=12`:null,revision,120);
  function toggle(){if(!open){try{const restored=readTagRules(filters);setLogic(restored.mode);setRules(restored.rules);setMode(filters.tag||filters.tag_predicate?'rules':filters.tagged?'tagged':'all_epochs');setError('');}catch(e){setError(e.message);}}setOpen(value=>!value);}
  function update(index,changes){setRules(old=>old.map((rule,i)=>i===index?{...rule,...changes}:rule));}
  function apply(event){event.preventDefault();try{const next=clearTagFilters(filters);if(mode==='rules')next.tag_predicate=JSON.stringify(compileTagRules(logic,rules));if(mode==='tagged')next.tagged='true';setOpen(false);onChange(next);}catch(e){setError(e.message);}}
  return <div className="protocol-view-filter"><button disabled={disabled} aria-expanded={open} aria-controls="protocol-view-filter-panel" onClick={toggle} className={active?'active':''}><ListFilter size={15}/> Filter{active&&<span className="filter-active-dot"/>}</button>{open&&<form id="protocol-view-filter-panel" className="protocol-view-filter-panel" onSubmit={apply}><header><strong>Filter this protocol</strong><button type="button" className="icon-button" aria-label="Close protocol filter" onClick={()=>setOpen(false)}><X size={14}/></button></header><p>Applies to both epoch views and exports.</p><label>Show<select value={mode} onChange={e=>setMode(e.target.value)}><option value="all_epochs">All epochs</option><option value="tagged">Tagged epochs</option><option value="rules">Tag rules</option></select></label>{mode==='rules'&&<><div className="tag-filter-logic"><select aria-label="Match tag rules" value={logic} onChange={e=>setLogic(e.target.value)}><option value="all">All</option><option value="any">Any</option></select><span>of these rules match</span></div>{rules.map((rule,index)=><div className="tag-filter-rule" key={index}><select aria-label={`Tag scope ${index+1}`} value={rule.scope} onChange={e=>update(index,{scope:e.target.value})}><option value="effective">Shared tags</option><option value="epoch">Epoch tags</option><option value="cell">Cell tags</option></select><select aria-label={`Tag comparison ${index+1}`} value={rule.comparison} onChange={e=>update(index,{comparison:e.target.value})}><option value="is">is</option><option value="is_not">is not</option></select><input aria-label={`Tag value ${index+1}`} value={rule.value} onChange={e=>{update(index,{value:e.target.value});setQuery(e.target.value);}} placeholder="Tag name" list="protocol-view-tag-options"/><button type="button" aria-label={`Remove tag rule ${index+1}`} disabled={rules.length===1} onClick={()=>setRules(old=>old.filter((_,i)=>i!==index))}><Trash2 size={13}/></button></div>)}<datalist id="protocol-view-tag-options">{(options.data?.tags||[]).map(item=><option key={item.tag} value={item.tag}/>)}</datalist><button type="button" disabled={rules.length>=20} onClick={()=>setRules(old=>[...old,blank()])}><Plus size={13}/> Add tag rule</button><p>Tags match whole saved names. Shared tags include inherited cell tags.</p></>}{error&&<p role="alert">{error}</p>}<footer>{active&&<button type="button" onClick={()=>{setOpen(false);onChange(clearTagFilters(filters));}}>Clear filter</button>}<button className="primary" disabled={disabled}>Apply filter</button></footer></form>}</div>;
}
