import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,ChevronDown,LoaderCircle,Plus,Sparkles,Pin,Database,Users,Activity,Clock3,CalendarDays,FileCheck2,X} from 'lucide-react';
import {api,humanize,time,number,duration} from '../api.js';
import ProtocolDiff,{CompactProtocolDiff} from './ProtocolDiff.jsx';
import {approveProtocolSuggestion} from '../protocolSuggestions.js';
import './ProtocolSuggestion.css';
import {importReadiness,suggestionDates} from '../importReadiness.js';

export default function ProtocolSuggestion({suggestion,onChange,onReview,onProtocol,importView=false,disabled=false,approvalSignal=0,onBusyChange}){
  const [comparison,setComparison]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[applied,setApplied]=useState(false);
  const lastSignal=useRef(approvalSignal);
  useEffect(()=>{if(approvalSignal!==lastSignal.current){lastSignal.current=approvalSignal;void add();}},[approvalSignal]);
  if(!suggestion)return null;
  const shown=comparison || suggestion;
  const alreadyApplied=applied||suggestion.status==='applied';
  async function add(){
    if(busy||alreadyApplied||suggestion.status!=='pending')return;
    setBusy(true);onBusyChange?.(true);setError('');setMessage('');
    try{
      const result=await approveProtocolSuggestion(suggestion,shown,api);
      if(!result.applied){setComparison(result.comparison);setMessage('The dataset or inspection state changed. Review this refreshed comparison, then approve it individually.');return;}
      setApplied(true);setMessage('Matched data added to this protocol. Inspection and exports now use the updated dataset.');onChange?.();
    }catch(error){setError(error.message);}finally{setBusy(false);onBusyChange?.(false);}
  }
  const removing=(shown.diff_counts?.removed || 0)>0;
  return <section className={`protocol-new-data ${importView?'import-ready-protocol':''} ${alreadyApplied?'is-added':''}`} aria-label={importView?humanize(suggestion.protocol_name):"New data matching saved protocol query"}>
    <div className="protocol-new-data-heading"><Sparkles size={19}/><div><h2>{importView?humanize(suggestion.protocol_name):suggestion.status==='stale'?'Saved proposal needs a refresh':'New data matches your saved query'}</h2><p>{suggestion.source_filename || 'Imported recording'} · {time(suggestion.created_at)}</p></div>{importView&&<span className={`import-ready-state ${alreadyApplied?'added':''}`}>{alreadyApplied?<Check size={13}/>:suggestion.status==='stale'?<Clock3 size={13}/>:<Sparkles size={13}/>} {alreadyApplied?'Added':suggestion.status==='stale'?'Refresh needed':'Ready to add'}</span>}</div>
    {importView?<ReadinessVisual suggestion={shown}/>:<CompactProtocolDiff comparison={shown}/>}{suggestion.status==='stale'&&<p className="protocol-new-data-note" role="status">Source membership changed after this proposal was saved. Open the protocol and use Refresh & compare to regenerate it before adding data.</p>}
    <div className="protocol-suggestion-actions"><button className="primary" disabled={disabled||busy||alreadyApplied||suggestion.status==='stale'} onClick={add}>{busy?<LoaderCircle size={15} className="spin"/>:alreadyApplied?<Check size={15}/>:<Plus size={15}/>} {busy?'Checking & adding…':alreadyApplied?'Added':importView?'Approve':removing?'Apply dataset update':'Add matched data'}</button>{onReview&&!alreadyApplied&&<button disabled={disabled||busy} onClick={()=>onReview(suggestion.candidate_revision_uuid,suggestion.protocol_uuid)}>Inspect changes <ArrowRight size={14}/></button>}{importView&&onProtocol&&<button className="quiet" onClick={()=>onProtocol(suggestion.protocol_uuid)}>Open protocol <ArrowRight size={13}/></button>}<span>{removing?'This proposal includes removals.':'Existing inspection decisions are preserved.'}</span></div>
    <details className="protocol-suggestion-details" open={!!comparison}><summary><ChevronDown size={13}/> See affected cells & epochs</summary><ProtocolDiff comparison={shown}/></details>
    {message&&<p className="protocol-new-data-note" role="status">{message}</p>}
    {error&&<div className="error" role="alert">{error}<p>Open the protocol and use Refresh & compare if the source or saved query changed. Check Activity & logs before retrying an interrupted request.</p></div>}
  </section>;
}
function ReadinessVisual({suggestion}){
  const summary=suggestion.diff_summary||{},current=summary.current||{},proposed=summary.proposed||{},delta=summary.delta||{},diff=suggestion.diff_counts||{};
  const dates=suggestionDates(suggestion),added=diff.added||0,removed=diff.removed||0,retained=Math.max(0,(current.epochs||0)-removed),scale=Math.max(1,retained+added);
  return <div className="import-ready-visual"><div className="import-ready-metrics"><div><span><Users size={14}/> Cells</span><strong>{number(current.cells)} <ArrowRight size={15}/> {number(proposed.cells)}</strong><small>{delta.cells>0?`+${number(delta.cells)} net new`:delta.cells<0?`${number(delta.cells)} net change`:'Same cells'}</small></div><div><span><Activity size={14}/> Epochs</span><strong className="import-new-count">+{number(added)}</strong><small>{number(current.epochs)} → {number(proposed.epochs)} in dataset</small></div><div><span><Clock3 size={14}/> Net recorded time</span><strong>{delta.duration_seconds==null?'—':`${delta.duration_seconds>=0?'+':'−'}${duration(Math.abs(delta.duration_seconds))}`}</strong><small>{proposed.duration_seconds==null?'Duration not recorded':`${duration(proposed.duration_seconds)} total`}</small></div></div><div className="import-membership-bar" role="img" aria-label={`${retained} retained epochs and ${added} added epochs; ${removed} removed`}><i style={{width:`${retained/scale*100}%`}}/><i className="new" style={{width:`${added/scale*100}%`}}/></div><div className="import-membership-caption"><span><i/>{number(retained)} retained</span><span><i className="new"/>+{number(added)} added</span>{removed>0&&<strong className="import-removal">−{number(removed)} removed</strong>}{diff.changed>0&&<strong>{number(diff.changed)} metadata changed</strong>}{dates.length>0&&<span className="import-ready-dates"><CalendarDays size={12}/>{dates.join(' · ')}{Object.values(summary.cell_changes?.truncated||{}).some(Boolean)?' · dates shown':''}</span>}</div></div>;
}
function readPins(projectId){try{return JSON.parse(localStorage.getItem(`rieke-os.sidebar.protocols.v1.${projectId}`))||{};}catch{return {};}}
export function ImportSuggestions({suggestions=[],protocols=[],projectId,sources=[],jobs=[],onReview,onProtocol,onChange,autoOpenJobUuid=null,dialogOnly=false,reviewLoading=false}){
  const [preferences,setPreferences]=useState(()=>readPins(projectId));
  const [approvalSignal,setApprovalSignal]=useState(0),[busyCount,setBusyCount]=useState(0),[open,setOpen]=useState(false);
  const dialogRef=useRef(null);
  const busy=busyCount>0;
  function busyChanged(value){setBusyCount(count=>Math.max(0,count+(value?1:-1)));}
  useEffect(()=>{const update=()=>setPreferences(readPins(projectId));update();window.addEventListener('storage',update);window.addEventListener('rieke-protocol-shortcuts-changed',update);return()=>{window.removeEventListener('storage',update);window.removeEventListener('rieke-protocol-shortcuts-changed',update);};},[projectId]);
  const model=importReadiness({suggestions,protocols,preferences});
  const latest=(autoOpenJobUuid&&jobs.find(job=>job.job_uuid===autoOpenJobUuid))||[...jobs].filter(job=>job&&(['complete','completed','success'].includes(job.status)||(job.status==='complete_with_warnings'&&job.catalog_committed===true))).sort((a,b)=>String(b.finished_at).localeCompare(String(a.finished_at)))[0];
  const catalogDelta=latest?.catalog_delta||latest?.progress?.catalog_delta;
  const source=sources.find(item=>item.source_sha256===latest?.source_sha256)||(latest?{filename:latest.source?.split?.('/').pop()||latest.filename||'Imported recording',counts:latest.progress?.counts}:null);
  useEffect(()=>{if(autoOpenJobUuid)setOpen(true);},[autoOpenJobUuid]);
  useEffect(()=>{if(open&&!dialogRef.current?.open)dialogRef.current?.showModal();else if(!open&&dialogRef.current?.open)dialogRef.current.close();},[open,latest?.job_uuid,suggestions.length]);
  if(!suggestions.length&&!latest)return null;
  const render=item=><ProtocolSuggestion key={item.suggestion_uuid||item.protocol_uuid} suggestion={item} onChange={onChange} onProtocol={id=>{setOpen(false);onProtocol?.(id);}} onReview={(...args)=>{setOpen(false);onReview?.(...args);}} importView disabled={busy||reviewLoading} approvalSignal={approvalSignal} onBusyChange={busyChanged}/>;
  const summary=<section className="import-readiness" aria-label="Import readiness summary"><header className="import-readiness-heading"><div><div className="eyebrow">IMPORT WORKBENCH</div><h2><FileCheck2 size={23}/> {model.ready>0?'Ready to add to your protocols.':'Protocol matching summary.'}</h2><p>Review the catalog import, then approve matching data for your pinned protocols.</p></div><span className="import-ready-total">{model.ready} ready{model.added>0?` · ${model.added} added`:''}{model.stale>0?` · ${model.stale} need refresh`:''}</span></header>{source&&<div className="import-source-summary"><Database size={21}/><div><strong>{source.filename}</strong><small>Latest completed import · {time(latest.finished_at)}</small></div><span><strong>{number(source.counts?.cells)}</strong> cells in imported source</span><span><strong>{number(source.counts?.epochs)}</strong> epochs in imported source</span><span className="import-checked"><Check size={14}/> Imported</span></div>}{catalogDelta&&<div className="import-catalog-delta" aria-label="Added to overall data store"><h3><Database size={16}/> Added to the overall data store</h3><div>{[['sources_added','recordings'],['cells_added','cells'],['epochs_added','epochs'],['responses_added','responses'],['stimuli_added','stimuli']].filter(([key])=>Number.isInteger(catalogDelta[key])).map(([key,label])=><span key={key}><strong>+{number(catalogDelta[key])}</strong> {label}</span>)}</div><p>New catalog records from this import. Protocol updates below are approved separately.</p></div>}{latest?.recording_storage?.verified&&latest?.recording_storage?.original_removal_safe&&<p className="import-managed-copy"><Check size={15}/> Saved a verified copy in this project. You can remove the original H5 from Downloads; keep the project copy.</p>}{latest?.warnings?.length>0&&<p className="error">Some post-import checks need attention. See import diagnostics below.</p>}
  {reviewLoading&&<p className="import-managed-copy" role="status"><LoaderCircle size={15} className="spin"/> Refreshing catalog totals and protocol matches…</p>}{model.pinned.length>0&&<div className="import-priority-group"><h3><Pin size={14}/> Pinned protocols</h3>{model.pinned.map(({protocol,suggestion})=>suggestion?render(suggestion):<div className="import-no-match" key={protocol.protocol_uuid}><div><strong>{humanize(protocol.name)}</strong><small>No pending proposal. Open the protocol to check its saved query.</small></div><button onClick={()=>onProtocol(protocol.protocol_uuid)}>Open protocol <ArrowRight size={13}/></button></div>)}</div>}
  {model.other.length>0&&<details className="import-other-protocols" open={!model.pinned.some(row=>row.suggestion?.status==='pending')}><summary>{model.pinned.length?'Other saved protocols':'Saved protocol matches'} <span>{model.other.length}</span></summary>{model.other.map(render)}</details>}
  <div className="import-review-actions"><button className="primary" disabled={busy||reviewLoading||!model.ready} onClick={()=>setApprovalSignal(value=>value+1)}>{busy?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>} {busy?'Checking updates…':'Approve All'}</button><span>Approves all pending protocol updates shown here. Each update is checked again before applying.</span></div><p className="import-readiness-footnote">Approval updates the protocol dataset and records its query and diff. Exports are available from each protocol. Cells may appear in more than one protocol.</p></section>;
  return <>{!dialogOnly&&<div className="import-review-launcher"><FileCheck2 size={18}/><span>{latest?'Import complete · review added data and protocol matches':'Protocol updates ready for review'}</span><button onClick={()=>setOpen(true)}>Review import</button></div>}{!dialogOnly&&!open&&summary}<dialog ref={dialogRef} className="import-review-dialog" onCancel={event=>{if(busy)event.preventDefault();else setOpen(false);}} onClose={()=>setOpen(false)} aria-labelledby="import-review-title"><header><div><h2 id="import-review-title">Review imported data</h2><p>Closing this review leaves unapproved protocol updates pending.</p></div><button className="icon-button" disabled={busy} aria-label="Close import review" onClick={()=>setOpen(false)}><X size={18}/></button></header>{open&&summary}<footer><button disabled={busy} onClick={()=>setOpen(false)}>Done reviewing</button></footer></dialog></>;
}
