"""Compact durable current-state recovery, independent of the live SQL store.

There is one compressed after-image per canonical primary key, not one snapshot
per edit. SQLite commits the changed rows and coverage watermark together. The
small JSON pointer is published only after the first database is durable. Old
v1 snapshots remain readable through workspace_state_snapshot.load.
"""
from __future__ import annotations

import datetime as dt
from contextlib import closing, contextmanager
import hashlib
import json
import logging
import os
from pathlib import Path
import re
import sqlite3
import struct
import tempfile
import uuid
import zlib

FORMAT = 'rieke-app-state'
VERSION = 2
CURRENT_PATTERN = re.compile(r'current-[0-9a-f]{32}\.sqlite\Z')
CHECKPOINT_PATTERN = re.compile(r'checkpoint-v2-\d{4}-\d{2}-\d{2}\.sqlite\Z')
# Only checkpoints generated by this version are automatically retired. Older
# backups and explicit before-restore snapshots remain under the user's control.
CHECKPOINT_COUNT = 2
CHECKPOINT_BYTES = 128 * 1024 * 1024


def _json(value):
    from workspace_state_snapshot import serialized
    return serialized(value)


def _pack(value):
    raw = _json(value).encode('utf-8')
    compressed = zlib.compress(raw, 6)
    return (b'z' + compressed if len(compressed) < len(raw) else b'j' + raw)


def _unpack(blob):
    if not isinstance(blob, bytes) or not blob or blob[:1] not in (b'z', b'j'):
        raise ValueError('Invalid recovery row encoding')
    try:
        raw = zlib.decompress(blob[1:]) if blob[:1] == b'z' else blob[1:]
        return json.loads(raw)
    except (ValueError, zlib.error, UnicodeError) as error:
        raise ValueError('Invalid recovery row data') from error


def _digest(table, key, blob):
    return hashlib.sha256(str(table).encode() + b'\0' + key + b'\0' + blob).digest()


def _key_blob(values):
    """Lossless typed keys, with ordinary UUID strings stored in sixteen bytes."""
    result = bytearray()
    for value in values:
        try:
            identity = uuid.UUID(value) if isinstance(value, str) else None
        except ValueError:
            identity = None
        if identity is not None and str(identity) == value:
            result.extend(b'u' + identity.bytes)
        else:
            data = _json(value).encode()
            result.extend(b'j' + struct.pack('>I', len(data)) + data)
    return bytes(result)


def _key_values(blob):
    result = []
    offset = 0
    try:
        while offset < len(blob):
            kind = blob[offset:offset+1]
            offset += 1
            if kind == b'u':
                result.append(str(uuid.UUID(bytes=blob[offset:offset+16])))
                offset += 16
            elif kind == b'j':
                size = struct.unpack('>I', blob[offset:offset+4])[0]
                offset += 4
                if offset + size > len(blob):
                    raise ValueError('Truncated recovery key')
                result.append(json.loads(blob[offset:offset+size]))
                offset += size
            else:
                raise ValueError('Unsupported recovery key')
    except (ValueError, struct.error, UnicodeError) as error:
        raise ValueError('Invalid recovery key') from error
    return result


def _accumulate(seal, digest, delta):
    seal['count'] += delta
    seal['xor'] = (int(seal['xor'], 16) ^ int.from_bytes(digest, 'big')).to_bytes(32, 'big').hex()


def _remove_row(database, table, key, seal, table_seal):
    old = database.execute('SELECT sha256 FROM recovery_rows WHERE table_name=? AND row_key=?', (table, key)).fetchone()
    if old is not None:
        _accumulate(seal, old[0], -1)
        _accumulate(table_seal, old[0], -1)
        database.execute('DELETE FROM recovery_rows WHERE table_name=? AND row_key=?', (table, key))


def _directory_sync(path):
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _regular(path):
    if any(parent.is_symlink() for parent in (path, *path.parents)):
        raise ValueError('Recovery files cannot follow symbolic links')
    if path.exists() and not path.is_file():
        raise ValueError('Recovery state must be a regular file')


def _folder(root):
    folder = root / 'backups' / 'app-state'
    for path in (root / 'backups', folder):
        if path.is_symlink():
            raise ValueError('Recovery directories cannot be symbolic links')
        if not path.exists():
            path.mkdir()
            _directory_sync(path.parent)
    return folder


def pointer_path(root, pointer):
    if (set(pointer) != {'format', 'version', 'project_uuid', 'store_uuid', 'store'}
            or pointer.get('format') != FORMAT or pointer.get('version') != VERSION):
        raise ValueError('Unsupported recovery pointer')
    name = 'current-' + str(pointer['store_uuid']).replace('-', '') + '.sqlite'
    try:
        identity = str(uuid.UUID(pointer['store_uuid']))
        project = str(uuid.UUID(pointer['project_uuid']))
    except (ValueError, TypeError, AttributeError) as error:
        raise ValueError('Invalid recovery identity') from error
    if (identity != pointer['store_uuid'] or project != pointer['project_uuid']
            or not CURRENT_PATTERN.fullmatch(name)
            or pointer['store'] != 'backups/app-state/' + name):
        raise ValueError('Invalid recovery pointer path')
    path = Path(root) / pointer['store']
    _regular(path)
    return path


@contextmanager
def _connect(path, *, readonly=False):
    _regular(path)
    for suffix in ('-journal', '-wal', '-shm'):
        _regular(Path(str(path) + suffix))
    if readonly:
        # A killed writer can leave a hot rollback journal after dirty pages
        # reached the main file. SQLite must replay it before a read; mode=ro
        # prevents that repair. Only mutable current mirrors open mode=rw (never
        # create); SQLite's own locks arbitrate recovery with live writers. Sealed
        # daily/legacy snapshots stay read-only. Never ignore/delete a journal.
        mutable = CURRENT_PATTERN.fullmatch(path.name) is not None
        database = sqlite3.connect(path.absolute().as_uri() + ('?mode=rw' if mutable else '?mode=ro'), uri=True)
        try:
            database.execute('PRAGMA schema_version').fetchone()
            database.execute('PRAGMA query_only=ON')
        except BaseException:
            database.close()
            raise
    else:
        database = sqlite3.connect(path, timeout=30)
        database.execute('PRAGMA journal_mode=DELETE')
        # EXTRA includes the directory sync after removing a rollback journal.
        database.execute('PRAGMA synchronous=EXTRA')
        database.execute('PRAGMA foreign_keys=ON')
    try:
        with database:
            yield database
    finally:
        database.close()


def _metadata(database, *, expected=None):
    rows = database.execute('SELECT payload,sha256 FROM recovery_header').fetchall()
    if len(rows) != 1:
        raise ValueError('Expected one recovery header')
    blob, digest = rows[0]
    if hashlib.sha256(blob).digest() != digest:
        raise ValueError('Recovery header checksum differs')
    header = _unpack(blob)
    from workspace_state_snapshot import TABLES
    if (header.get('format') != FORMAT or header.get('version') != VERSION
            or set(header.get('keys', {})) - set(TABLES)
            or set(header.get('columns', {})) != set(header.get('keys', {}))
            or set(header.get('state', {}).get('tables', {})) != set(TABLES)
            or any(header['state']['tables'].values())):
        raise ValueError('Unsupported recovery header')
    table_seals = header.get('table_seals')
    if table_seals is not None and (set(table_seals) != set(TABLES) or any(
            not isinstance(value, dict) or set(value) != {'count', 'xor'}
            or type(value['count']) is not int or value['count'] < 0
            or not isinstance(value['xor'], str) or not re.fullmatch(r'[0-9a-f]{64}', value['xor'])
            for value in table_seals.values())):
        raise ValueError('Invalid recovery table content seals')
    if expected is not None and (header['store_uuid'] != expected['store_uuid']
            or header['state']['project']['project_uuid'] != expected['project_uuid']):
        raise ValueError('Recovery pointer and database identity differ')
    return header


def inspect(root):
    """Read the durable watermark without reading all canonical rows."""
    root = Path(root).resolve()
    target = root / 'app-state.json'
    _regular(target)
    if not target.exists():
        return None
    pointer = json.loads(target.read_text())
    if pointer.get('version') == 1:
        return None
    path = pointer_path(root, pointer)
    with _connect(path, readonly=True) as database:
        header = _metadata(database, expected=pointer)
    return {'pointer': pointer, 'path': path, 'header': header}


def verified_table_content(root, tracker, tables=('shared_annotation', 'annotation_profile')):
    """Prove content seals against the live authority, never a saved old token.

    This is a checkpoint/startup operation. The caller also fences its derived
    index and immutable metadata generation around checkpoint publication.
    """
    try:
        before = tracker.token()
        if before is None:
            return None
        current = inspect(root)
        if current is None:
            return None
        header = current['header']
        seals = header.get('table_seals')
        if (not isinstance(seals, dict) or any(table not in seals for table in tables)
                or before != header['watermark'] or tracker.token() != before
                or before.get('project_uuid') != header['state']['project']['project_uuid']):
            return None
        return {'project_uuid': before['project_uuid'],
                'tables': {table: dict(seals[table]) for table in tables}}
    except (OSError, ValueError, TypeError, KeyError, sqlite3.Error):
        return None


def _row_key(row, names):
    if not names or any(name not in row or row[name] is None for name in names):
        raise ValueError('Recovery row has an invalid primary key')
    return _key_blob([row[name] for name in names if name != 'project_uuid'])


def _write_rows(database, tables, keys, columns, project_uuid, seal, table_seals, *, replace):
    from workspace_state_snapshot import TABLES
    for table, rows in tables.items():
        if rows and table not in keys:
            raise ValueError('Recovery table has no primary-key contract')
        seen = set() if replace else None
        for row in rows:
            if row.get('project_uuid') != project_uuid:
                raise ValueError('Recovery contains a foreign project row')
            key = _row_key(row, keys[table])
            if seen is not None:
                if key in seen:
                    raise ValueError('Duplicate primary key in recovery after-images')
                seen.add(key)
            if set(row) != set(columns[table]):
                raise ValueError('Recovery row columns differ')
            values = [row[name] for name in columns[table] if name not in keys[table] and name != 'project_uuid']
            blob = _pack(values)
            table_id = TABLES.index(table)
            if replace:
                _remove_row(database, table_id, key, seal, table_seals[table])
            digest = _digest(table_id, key, blob)
            database.execute('INSERT INTO recovery_rows VALUES (?,?,?,?)', (table_id, key, blob, digest))
            _accumulate(seal, digest, 1)
            _accumulate(table_seals[table], digest, 1)


def _validate_keys(keys):
    from workspace_state_snapshot import TABLES
    if set(keys) - set(TABLES) or any(not isinstance(names, (list, tuple)) or not names
            or len(set(names)) != len(names) or any(not isinstance(name, str) or not name for name in names)
            for names in keys.values()):
        raise ValueError('Invalid recovery primary-key contract')


def write(root, *, state, keys, watermark, columns=None, changes=None, deleted=None, day=None):
    """Commit a complete snapshot, or verified gap-covering after-images.

    The caller holds .app-state-save.lock and proves SQL coverage. ``state`` has
    the complete current file/source header; with changes it has empty tables.
    Keys and watermark are published in the same SQLite transaction as rows.
    """
    root = Path(root).resolve()
    _validate_keys(keys)
    from workspace_state_snapshot import TABLES, atomic_write
    if state.get('format') != FORMAT or state.get('version') != 1 or set(state.get('tables', {})) != set(TABLES):
        raise ValueError('Invalid complete recovery state')
    project_uuid = state['project']['project_uuid']
    try:
        if str(uuid.UUID(project_uuid)) != project_uuid:
            raise ValueError('Recovery requires a canonical project UUID')
    except (TypeError, AttributeError) as error:
        raise ValueError('Recovery requires a canonical project UUID') from error
    current = inspect(root)
    if columns is None:
        columns = current['header']['columns'] if current else {
            table: list(rows[0]) if rows else list(keys[table])
            for table, rows in state['tables'].items() if table in keys}
    if (set(columns) != set(keys) or any(not isinstance(names, (list, tuple))
            or len(set(names)) != len(names) or not set(keys[table]) <= set(names)
            or 'project_uuid' not in names for table, names in columns.items())):
        raise ValueError('Invalid recovery column contract')
    if changes is not None and current is None:
        raise ValueError('Incremental recovery requires a durable baseline')
    if current is not None and current['pointer']['project_uuid'] != project_uuid:
        raise ValueError('Recovery baseline belongs to a different project')
    if changes is not None and not current['header'].get('table_seals'):
        raise ValueError('Incremental recovery requires a content-sealed baseline')
    if changes is not None and (keys != current['header']['keys'] or columns != current['header']['columns']):
        raise ValueError('Incremental recovery key contract changed')
    if changes is not None and any(state['tables'].values()):
        raise ValueError('Incremental recovery header must not duplicate table rows')
    folder = _folder(root)
    if (changes is not None and not any(changes.values()) and not any((deleted or {}).values())
            and state == current['header']['state'] and watermark == current['header']['watermark']):
        daily = checkpoint(current['path'], folder, day=day)
        return {'path': str(root / 'app-state.json'), 'bytes': current['path'].stat().st_size,
                'changed': False, 'daily_backup': str(daily), 'incremental': True,
                'recovery_storage': storage(root)}
    store_uuid = current['pointer']['store_uuid'] if current else str(uuid.uuid4())
    name = 'current-' + uuid.UUID(store_uuid).hex + '.sqlite'
    final_path = folder / name
    temporary = None
    if current:
        path = current['path']
    else:
        fd, temporary_name = tempfile.mkstemp(prefix='.recovery-', suffix='.sqlite', dir=folder)
        os.close(fd)
        temporary = path = Path(temporary_name)
    header = {'format': FORMAT, 'version': VERSION, 'store_uuid': store_uuid,
              'keys': keys, 'columns': columns, 'watermark': watermark,
              'seal': dict(current['header']['seal']) if changes is not None else {'count': 0, 'xor': '0' * 64},
              'table_seals': {table: dict(current['header']['table_seals'][table]) if changes is not None
                              else {'count': 0, 'xor': '0' * 64} for table in TABLES},
              'state': {**state, 'tables': {table: [] for table in TABLES}}}
    try:
        with _connect(path) as database:
            if not current:
                database.execute('PRAGMA auto_vacuum=INCREMENTAL')
                database.execute('CREATE TABLE recovery_header (payload BLOB NOT NULL,sha256 BLOB NOT NULL)')
                database.execute('CREATE TABLE recovery_rows (table_name INTEGER NOT NULL,row_key BLOB NOT NULL,'
                    'payload BLOB NOT NULL,sha256 BLOB NOT NULL,PRIMARY KEY(table_name,row_key)) WITHOUT ROWID')
                database.commit()
            database.execute('BEGIN IMMEDIATE')
            if changes is None:
                database.execute('DELETE FROM recovery_rows')
            else:
                if set(changes) - set(keys) or set(deleted or {}) - set(keys):
                    raise ValueError('Incremental recovery references an unsupported table')
                for table, identities in (deleted or {}).items():
                    for identity in identities:
                        if len(identity) != len(keys[table]):
                            raise ValueError('Invalid recovery deletion key')
                        key = _key_blob([value for name, value in zip(keys[table], identity) if name != 'project_uuid'])
                        if 'project_uuid' in keys[table] and identity[keys[table].index('project_uuid')] != project_uuid:
                            raise ValueError('Recovery deletion belongs to a different project')
                        _remove_row(database, TABLES.index(table), key, header['seal'], header['table_seals'][table])
            _write_rows(database, state['tables'] if changes is None else changes, keys, columns,
                        project_uuid, header['seal'], header['table_seals'], replace=changes is not None)
            packed = _pack(header)
            database.execute('DELETE FROM recovery_header')
            database.execute('INSERT INTO recovery_header VALUES (?,?)', (packed, hashlib.sha256(packed).digest()))
            database.commit()
            # Reuse freed pages between edits; bound reclamation work per save.
            database.execute('PRAGMA incremental_vacuum(64)')
        # Explicit barrier also makes injected I/O failures observable before an
        # acknowledgment. Initial publication additionally syncs its directory.
        with path.open('rb') as handle:
            os.fsync(handle.fileno())
        if temporary is not None:
            os.replace(temporary, final_path)
            _directory_sync(folder)
            pointer = dict(format=FORMAT, version=VERSION, project_uuid=project_uuid,
                           store_uuid=store_uuid, store='backups/app-state/' + name)
            atomic_write(root / 'app-state.json', _json(pointer).encode())
        daily = checkpoint(final_path, folder, day=day)
        _clean_orphans(root, final_path, project_uuid)
        return {'path': str(root / 'app-state.json'), 'bytes': final_path.stat().st_size,
                'changed': True, 'daily_backup': str(daily), 'incremental': changes is not None,
                'recovery_storage': storage(root)}
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
            Path(str(temporary) + '-journal').unlink(missing_ok=True)
            # atomic_write can publish the pointer and then raise at its final
            # directory barrier. Preserve that referenced database. When the
            # pointer definitely did not switch, a completed new file is only
            # an unacknowledged staging copy and must not accumulate on retries.
            try:
                target = root / 'app-state.json'
                published = json.loads(target.read_text()) if target.exists() else None
                known_old = published is None or published.get('version') == 1
                other_current = (published is not None and published.get('version') == 2
                    and pointer_path(root, published) != final_path)
                if final_path.exists() and (known_old or other_current):
                    final_path.unlink()
                    _directory_sync(folder)
            except (OSError, ValueError):
                # An unreadable pointer gives no authority to delete evidence.
                logging.getLogger(__name__).exception('Recovery staging cleanup could not verify the pointer')


def _clean_orphans(root, current, project_uuid):
    """Collect only verified unreferenced mirrors after a durable publication."""
    removed = False
    for path in current.parent.iterdir():
        if path == current or not CURRENT_PATTERN.fullmatch(path.name) or path.is_symlink():
            continue
        try:
            with _connect(path, readonly=True) as database:
                header = _metadata(database)
            expected = 'current-' + uuid.UUID(header['store_uuid']).hex + '.sqlite'
            if path.name != expected or header['state']['project']['project_uuid'] != project_uuid:
                continue
            path.unlink()
            removed = True
        except (OSError, ValueError, sqlite3.Error):
            logging.getLogger(__name__).warning('Preserving an unverified recovery file: %s', path)
    if removed:
        _directory_sync(current.parent)


def checkpoint(current, folder, *, day=None):
    date = dt.date.fromisoformat(day or dt.datetime.now(dt.timezone.utc).date().isoformat()).isoformat()
    daily = folder / ('checkpoint-v2-' + date + '.sqlite')
    _regular(daily)
    if not daily.exists():
        fd, name = tempfile.mkstemp(prefix='.checkpoint-', suffix='.sqlite', dir=folder)
        os.close(fd)
        temporary = Path(name)
        try:
            with _connect(current, readonly=True) as source, closing(sqlite3.connect(temporary)) as destination:
                source.backup(destination)
                destination.execute('VACUUM')
            with temporary.open('rb') as handle:
                os.fsync(handle.fileno())
            os.chmod(temporary, 0o400)
            try:
                os.link(temporary, daily)
            except FileExistsError:
                pass
            _directory_sync(folder)
        finally:
            temporary.unlink(missing_ok=True)
    # Keep the newest checkpoint even if it alone exceeds the history budget:
    # a storage budget cannot justify dropping the only previous recovery point.
    retained = sorted((p for p in folder.iterdir() if CHECKPOINT_PATTERN.fullmatch(p.name)), reverse=True)
    total = 0
    removed = False
    for number, path in enumerate(retained):
        _regular(path)
        size = path.stat().st_size
        if number and (number >= CHECKPOINT_COUNT or total + size > CHECKPOINT_BYTES):
            path.unlink()
            removed = True
        else:
            total += size
    if removed:
        _directory_sync(folder)
    return daily if daily.exists() else retained[0]


def storage(root):
    """Separate current state, managed history, and preserved older backups."""
    folder = Path(root) / 'backups' / 'app-state'
    counts = {'current_bytes': 0, 'checkpoint_bytes': 0, 'other_backup_bytes': 0,
              'checkpoint_count': 0, 'checkpoint_budget_bytes': CHECKPOINT_BYTES}
    for path in folder.iterdir():
        if path.is_symlink() or not path.is_file():
            continue
        size = path.stat().st_size
        if CURRENT_PATTERN.fullmatch(path.name):
            counts['current_bytes'] += size
        elif CHECKPOINT_PATTERN.fullmatch(path.name):
            counts['checkpoint_bytes'] += size
            counts['checkpoint_count'] += 1
        else:
            counts['other_backup_bytes'] += size
    counts['checkpoint_budget_exceeded'] = counts['checkpoint_bytes'] > CHECKPOINT_BYTES
    return counts


def load_database(path, *, expected=None):
    """Validate the entire current-state mirror before exposing restore input."""
    with _connect(Path(path), readonly=True) as database:
        database.execute('BEGIN')
        if database.execute('PRAGMA quick_check').fetchall() != [('ok',)]:
            raise ValueError('Recovery database integrity check failed')
        header = _metadata(database, expected=expected)
        state = header['state']
        from workspace_state_snapshot import TABLES
        seal = {'count': 0, 'xor': '0' * 64}
        table_seals = {table: {'count': 0, 'xor': '0' * 64} for table in TABLES}
        for table_id, key, blob, digest in database.execute(
                'SELECT table_name,row_key,payload,sha256 FROM recovery_rows ORDER BY table_name,row_key'):
            if type(table_id) is not int or not 0 <= table_id < len(TABLES):
                raise ValueError('Recovery contains an unknown table')
            table = TABLES[table_id]
            if table not in header['keys'] or _digest(table_id, key, blob) != digest:
                raise ValueError('Recovery row checksum or table differs')
            _accumulate(seal, digest, 1)
            _accumulate(table_seals[table], digest, 1)
            key_names = [name for name in header['keys'][table] if name != 'project_uuid']
            values = _key_values(key)
            nonkeys = [name for name in header['columns'][table] if name not in header['keys'][table] and name != 'project_uuid']
            data = _unpack(blob)
            if len(values) != len(key_names) or not isinstance(data, list) or len(data) != len(nonkeys):
                raise ValueError('Recovery row columns differ')
            row = dict(zip(key_names, values))
            row.update(zip(nonkeys, data))
            row['project_uuid'] = state['project']['project_uuid']
            if (_row_key(row, header['keys'][table]) != key
                    or row.get('project_uuid') != state['project']['project_uuid']):
                raise ValueError('Recovery row identity differs')
            state['tables'][table].append(row)
        if header.get('table_seals') is not None and table_seals != header['table_seals']:
            raise ValueError('Recovery table content seal differs')
        if seal != header['seal']:
            raise ValueError('Recovery row count or content seal differs')
        return state
